# Use Python base image
FROM python:3.11-slim

WORKDIR /app/server

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY ./utils.py /app/utils.py 

# COPY ./server /app/server/      

# Expose server port
EXPOSE 8080

# Run the Flower server
CMD ["python", "server.py"]
