services:
  # Server
  server:
    build:
      context: .  
      dockerfile: Dockerfile.server  
    container_name: flwr-server
    ports:
      - "8080:8080"
    environment:
      - NUM_ROUNDS=3
    restart: always
    volumes:
      - ./server:/app/server 

  # Client 0
  client0:
    build:
      context: . 
      dockerfile: Dockerfile.client  
    container_name: flwr-client0
    environment:
      - PARTITION_ID=0
      - SERVER_ADDRESS=server:8080
    volumes:
      - ./client:/app/client 
    depends_on:
      - server
    restart: always

  # Client 1
  client1:
    build:
      context: .  
      dockerfile: Dockerfile.client  
    container_name: flwr-client1
    environment:
      - PARTITION_ID=1
      - SERVER_ADDRESS=server:8080
    volumes:
      - ./client:/app/client 
    depends_on:
      - server
    restart: always

  # Client 2
  client2:
    build:
      context: . 
      dockerfile: Dockerfile.client  
    container_name: flwr-client2
    environment:
      - PARTITION_ID=2
      - SERVER_ADDRESS=server:8080
    volumes:
      - ./client:/app/client  
    depends_on:
      - server
    restart: always